### ISSUE TITLE
[SafeEmbedGenerator] Links are temporary ?

### ISSUE THREAD

**Issue by TheVolya** [KyzaGitHub/Khub#1]
Hello ! Thank you very much for you work, your plugin "SafeEmbedGenerator" is incredible.

I just have a small issue : it seems links are temporary ? Like **if i try to copy/paste an embed link that i created some hours ago, the embed won't show anymore.**
Is it intended ? If it is, is there a way to avoid that ?
I'm working on a big RPG game with items being shown as embed messages, but if we can't copy/paste theses whenever we want, it won't be very practical :(

Thank you in advance !

**Comment by KyzaGitHub** [comment]
This is actually something I am working on. The embed generator relies on an API to host the embeds, this API only keeps the embeds for 5 minutes before deleting them. What I will be adding in the next update is a way to save embeds so that you can regenerate them quickly by clicking on them. You will get a different link every time, but the embeds will be saved so that you can quickly send ones that you have already made.
